# Generated by Django 5.0.6 on 2024-06-19 20:25

from django.db import migrations, models

class Migration(migrations.Migration):
  dependencies = [
    ('myfirstapp', '0001_initial'),
  ]

  operations = [
    migrations.AddField(
      model_name='myfirstmodel',
      name='description',
      field=models.TextField(default=''),
    ),
  ]
